// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type DashboardCardData = {
    total_users: number;
    total_items: number;
    active_users: number;
    inactive_items: number;
};

export type DashboardData = {
    cards: DashboardCardData;
    revenue: Array<RevenueData>;
    items: Array<ItemPublic>;
};

export type HistoricalDataGroupedResponse = {
    series: Array<TimeSeriesData>;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    tenant_id: string;
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreateInput = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type RevenueData = {
    month: string;
    revenue: number;
};

export type ScheduleRow = {
    rec_no: number;
    start_time: string;
    end_time: (string | null);
    charge_enable: boolean;
    charge_from_grid: boolean;
    discharge_enable: boolean;
    allow_to_sell: boolean;
    charge_power: number;
    charge_limit: number;
    discharge_power: number;
    source: number;
    id: number;
    updated_at: string;
};

export type TenantCreate = {
    name: string;
    description?: (string | null);
};

export type TenantPublic = {
    name: string;
    description?: (string | null);
    id: string;
};

export type TenantsPublic = {
    data: Array<TenantPublic>;
    count: number;
};

export type TenantUpdate = {
    name?: (string | null);
    description?: (string | null);
};

export type TimeSeriesData = {
    data_id: number;
    name: string;
    data: Array<TimeSeriesPoint>;
};

export type TimeSeriesPoint = {
    x: number;
    y: (number | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: (string | null);
    password: string;
    tenant_id: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    role?: string;
    id: string;
    tenant_id: string;
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    password?: (string | null);
    full_name?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    role?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type DashboardReadDashboardDataData = {
    /**
     * Admin override to view a specific tenant's dashboard
     */
    tenantIdOverride?: (string | null);
};

export type DashboardReadDashboardDataResponse = (DashboardData);

export type HistoricalDataReadHistoricalDetailsData = {
    /**
     * List of DATA_IDs to fetch
     */
    dataIds: Array<(number)>;
    /**
     * End timestamp (ISO format, optional)
     */
    end?: (string | null);
    /**
     * PLANT_ID to fetch data for
     */
    plantId: number;
    /**
     * Start timestamp (ISO format, optional)
     */
    start?: (string | null);
    /**
     * Admin override for tenant ID
     */
    tenantIdOverride?: (string | null);
};

export type HistoricalDataReadHistoricalDetailsResponse = (HistoricalDataGroupedResponse);

export type ItemsReadItemsData = {
    /**
     * Fetch items from all tenants (Superuser only)
     */
    allTenants?: boolean;
    limit?: number;
    skip?: number;
    /**
     * Filter by specific tenant ID (Superuser only)
     */
    tenantId?: (string | null);
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserWithNewTenantData = {
    requestBody: PrivateUserCreateInput;
};

export type PrivateCreateUserWithNewTenantResponse = (UserPublic);

export type ScheduleReadScheduleData = {
    /**
     * The date to fetch schedule for, in YYYY-MM-DD format
     */
    date: string;
    plantId: number;
    tenantDb: string;
};

export type ScheduleReadScheduleResponse = (Array<ScheduleRow>);

export type ScheduleBulkUpdateScheduleData = {
    date: string;
    plantId: number;
    requestBody: Array<ScheduleRow>;
    tenantDb: string;
};

export type ScheduleBulkUpdateScheduleResponse = (Array<ScheduleRow>);

export type TenantsCreateTenantData = {
    requestBody: TenantCreate;
};

export type TenantsCreateTenantResponse = (TenantPublic);

export type TenantsReadTenantsData = {
    limit?: number;
    skip?: number;
};

export type TenantsReadTenantsResponse = (TenantsPublic);

export type TenantsReadTenantByIdData = {
    tenantId: string;
};

export type TenantsReadTenantByIdResponse = (TenantPublic);

export type TenantsUpdateTenantData = {
    requestBody: TenantUpdate;
    tenantId: string;
};

export type TenantsUpdateTenantResponse = (TenantPublic);

export type TenantsDeleteTenantData = {
    tenantId: string;
};

export type TenantsDeleteTenantResponse = (Message);

export type UsersReadUsersData = {
    /**
     * Fetch users from all tenants (Superuser only)
     */
    allTenants?: boolean;
    limit?: number;
    skip?: number;
    /**
     * Filter by specific tenant ID (Superuser only)
     */
    tenantId?: (string | null);
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);